version: '3'

services:
  postgres:
    image: 'postgres:14.2'
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
      POSTGRES_DB: bot_dev
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data